### ISSUE TITLE
Elm compiler error about warn=true option

### ISSUE THREAD

**Issue by Tanneguy** [ceddlyburge/progressive-elm-app#1]
You may want to suppress the `&warn=true` option to webpack-dev-server invocation, it breaks the compilation

**Comment by Tanneguy** [comment]
The app does not display anything. The index.html is loaded but not the Elm code.

**Comment by ceddlyburge** [comment]
Hi Tann

This code does work, you can see it deployed at https://webpack-progressive-231355.netlify.com/.

I think you will be able to see the log for this deployment at https://app.netlify.com/sites/webpack-progressive-231355/deploys/5b32ad7f67610c508060490f. If not please let me know and I'll copy and paste the text.

I think the problem is happening because this is written in elm 0.18, and I assume you are using elm 0.19.

I'll update this to 0.19.

Cheers

Cedd

**Comment by ceddlyburge** [comment]
Hi Tann

I've updated the code to Elm 0.19 now, if you check out the master or webpack-progressive branches you will be able to see it working.

I've also updated the readme with some instructions on running it locally, and added a link to the deployment on Netlify.

Cheers

Cedd
